# Site settings
title: Proton的博客
SEOTitle: Proton的博客 | Proton's Blog
header-img: img/post-bg.jpg
email: chenproton@gmail.com
description: "."
keyword: "Proton, Proton Blog, Proton的博客, chenproton, 陈云龙的博客, 陈云龙"
url: "http://chenproton.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/chenproton/chenproton.github.io.git" # you code repository

# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "世界上只有两件事深深的震撼着人们的心灵"
sidebar-avatar: /img/post-bg.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     wowproton
zhihu_username:     wowchenproton
facebook_username:  ChenProton
jianshu_username:   43c752058783
#twitter_username:   chenproton




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: disqus_tzX2HqzTNt

<!-- Gitalk 评论 start  -->

<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script> 
<div id="gitalk-container"></div>     <script type="text/javascript">
    var gitalk = new Gitalk({

    // gitalk的主要参数
    clientID: `bedd6aaa68a92a48df53`,
    clientSecret: `1c87f820313216b0706dbcc7361325824c8b2810`,
    repo: `chenproton.github.io`,
    owner: 'chenproton',
    admin: ['chenproton'],
    id: 'window.location.pathname',
    
    });
    gitalk.render('gitalk-container');
</script> 
<!-- Gitalk end -->

# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: bedd6aaa68a92a48df53                            #生成的clientID
#  clientSecret: 1c87f820313216b0706dbcc7361325824c8b2810    #生成的clientSecret
#  repo: chenproton.github.io    #仓库名称
#  owner: chenproton    #github用户名
#  admin: chenproton
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: daxiaxia.com              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

